version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
      - "3306:3306"
   wordpress:
     depends_on:
       - db
     image: wordpress:php5.6-apache
     volumes:
       - ./wp-content:/var/www/html/wp-content/
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db:3306
      PMA_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - '8080:80'
volumes:
  db_data: